name: Build and Download JARs for Two Java Applications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [app1, app2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -f ${{ matrix.app }}/pom.xml clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.app }}-jar
          path: ${{ matrix.app }}/target/*.jar

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download app1 JAR
        uses: actions/download-artifact@v3
        with:
          name: app1-jar
          path: ./downloaded-artifacts/app1

      - name: Download app2 JAR
        uses: actions/download-artifact@v3
        with:
          name: app2-jar
          path: ./downloaded-artifacts/app2